name: Deploy d3-api-demo to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'

      - name: Install dependencies
        run: yarn install

      - name: Build the widget test app for production
        run: yarn build
        env:
          VITE_D3_API_KEY: ${{ secrets.VITE_D3_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
